{"timestamp": "2025-08-18T11:57:11.321576", "type": "error", "component": "sensor", "error_message": "No temperature data available for local API request"}
{"timestamp": "2025-08-18T11:57:53.122655", "type": "error", "component": "sensor", "error_message": "No temperature data available for local API request"}
{"timestamp": "2025-08-18T11:57:54.647524", "type": "error", "component": "sensor", "error_message": "No temperature data available for local API request"}
{"timestamp": "2025-08-19T10:26:46.298266", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023BE2961950>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))"}
{"timestamp": "2025-08-19T10:27:01.353789", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000023BE2961BD0>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T10:27:16.361172", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000023BE29607D0>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T10:27:31.367827", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000023BE2961A90>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T10:27:56.737842", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000023BE2961E50>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T10:28:11.752536", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000023BE2962210>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:38:43.079240", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D62D145590>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))"}
{"timestamp": "2025-08-19T11:38:58.084113", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D145BD0>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:39:13.089222", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D145F90>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:39:28.094471", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D145D10>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:39:43.099360", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D1465D0>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:39:58.103650", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D146990>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:40:13.111043", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D146E90>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:40:28.116979", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D146C10>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:40:43.122019", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D146850>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:40:58.126541", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D146490>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:41:13.131333", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D145090>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:41:28.135641", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D1460D0>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:41:43.140928", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D145E50>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-19T11:41:58.145706", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Max retries exceeded with url: /update (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001D62D147110>: Failed to resolve 'api.thingspeak.com' ([Errno 11001] getaddrinfo failed)\"))"}
{"timestamp": "2025-08-28T22:00:18.108717", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload failed with status 400"}
{"timestamp": "2025-08-28T22:00:35.256198", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload failed with status 400"}
{"timestamp": "2025-08-28T22:00:52.264991", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload failed with status 400"}
{"timestamp": "2025-08-28T22:01:09.419761", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload failed with status 400"}
{"timestamp": "2025-08-28T22:01:26.667715", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload failed with status 400"}
{"timestamp": "2025-08-28T22:01:42.869518", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload failed with status 400"}
{"timestamp": "2025-08-28T22:01:59.030921", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload failed with status 400"}
{"timestamp": "2025-08-28T22:02:15.243306", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload failed with status 400"}
{"timestamp": "2025-08-28T22:02:32.265207", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload failed with status 400"}
{"timestamp": "2025-08-28T22:02:49.904309", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload failed with status 400"}
{"timestamp": "2025-08-28T22:03:06.898030", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload failed with status 400"}
{"timestamp": "2025-08-28T22:03:23.130910", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload failed with status 400"}
{"timestamp": "2025-08-29T10:18:35.789829", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Read timed out. (read timeout=10)"}
{"timestamp": "2025-08-29T10:20:03.742284", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Read timed out. (read timeout=10)"}
{"timestamp": "2025-08-29T10:21:59.677928", "type": "error", "component": "sensor", "error_message": "ThingSpeak upload error: HTTPSConnectionPool(host='api.thingspeak.com', port=443): Read timed out. (read timeout=10)"}
